### PR TITLE
My submission

### PR DESCRIPTION
**Pull request by akmiller01**
Thanks for putting together this competition!

### CODE REVIEW

**Comment by LocalMicro** [comment]
Very impressive, akmiller! Although I am approaching this from a very different direction, my top restaurants are similar to yours, at least 12 of the 20 in your list are on my upper end. But I just want to mention something. The Michelin press release last week named 19 Bib Gourmands for Washington DC. If you look at the ration of BGs to Starred restaurants, you will see that there are many more (multiples) of BGs than there are starred restaurants. So at the very least, you could never have more than 18 starred restaurants, and it is much more likely that you would have less than a dozen starred.
Sharon (localmicro)

**Comment by akmiller01** [comment]
Thanks @LocalMicro . While I agree there may be fewer than 19 starred restaurants, I ultimately wanted to leave that decision up to my model. It decided to pick 21 restaurants out of a possible list of 42 (plus two bib gourmand I later removed), so I just rolled with it!

**Comment by akmiller01** [comment]
Preferred email alex.k.miller@gmail.com @josephofiowa

**Comment by josephofiowa** [comment]
Thanks! @akmiller01 Would be happy to hear where you picked up Lua. Best of luck in the competition -- results will be available tomorrow. Thanks to our friends at Michelin, we're aiming to be able to score and alert participants at the time of the list breaking.

**Comment by akmiller01** [comment]
I'm still just learning Torch and Lua, but this page has been a great help:
https://github.com/torch/torch7/wiki/Cheatsheet

**Pull request merged**
